version: '3.8'

services:

  backend:
    build: ./back
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydb

  frontend:
    build: ./webapp/citysafe
    container_name: react_app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  airflow-init:
    image: apache/airflow:2.8.1
    depends_on:
      - db
    environment:
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@db:5432/mydb
    entrypoint: >
      bash -c "
      airflow db init &&
      airflow users create --username admin --password admin --firstname admin --lastname user --role Admin --email admin@example.com
      "
    volumes:
      - ./airflow/dags:/opt/airflow/dags

  airflow-webserver:
    image: apache/airflow:2.8.1
    container_name: airflow_web
    restart: always
    depends_on:
      - airflow-init
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@db:5432/mydb
    volumes:
      - ./airflow/dags:/opt/airflow/dags

  airflow-scheduler:
    image: apache/airflow:2.8.1
    container_name: airflow_sched
    restart: always
    depends_on:
      - airflow-init
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@db:5432/mydb
    volumes:
      - ./airflow/dags:/opt/airflow/dags

volumes:
  db_data:
